package presentation.mainui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

import javax.swing.JTabbedPane;
import javax.swing.ImageIcon;

public class MainFrame{
	private JFrame frame;
    private int xOld = 0;
    private int yOld = 0;
    private JLabel jLabel1;
    private JLayeredPane jLayeredPane1;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JTabbedPane pane;
    
    /**
     * Creates new form NewFrame
     */
    public MainFrame(JTabbedPane pane) {
    	this.pane = pane;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	frame = new JFrame();
    	jPanel1 = new JPanel();

        jLayeredPane1 = new JLayeredPane();
        jPanel2 = new JPanel();
        
        jLayeredPane1.setLayout(new javax.swing.OverlayLayout(jLayeredPane1));
        
        JPanel panel_1 = new JPanel();
        
        panel_1.setBounds(0, 0, 800, 57);
		//panel_1.setBackground(Color.WHITE);
        panel_1.setOpaque(false);
		panel_1.setLayout(null);
		
		JLabel label = new JLabel("Welcome to NJWU~~ ");
		label.setBounds(25, 6, 396, 39);
		label.setForeground(Color.PINK);
		label.setFont(new Font("Libian SC",Font.PLAIN,33));
		
		panel_1.add(label);
		
		JButton button = new JButton("");
		button.setIcon(new ImageIcon(MainFrame.class.getResource("/image/logout.png")));
		button.setBounds(646, 6, 50, 50);
		button.setBorderPainted(false);
		button.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				//login
				frame.dispose();
				@SuppressWarnings("unused")
				LoginFrame l = new LoginFrame();
			}
		});
		jPanel2.setLayout(null);
		button.setContentAreaFilled(false);
		panel_1.add(button);
		
		jPanel2.add(panel_1);
		jPanel2.add(pane);
        jPanel2.setOpaque(false);
        JButton closeButton = new JButton();
        closeButton.setBorderPainted(false);
        closeButton.setBounds(780, 0, 20, 20);
        closeButton.setContentAreaFilled(false);
        closeButton.setIcon(new ImageIcon(MainFrame.class.getResource("/image/close.png")));
        closeButton.addActionListener(new ActionListener() {
        	@Override
        	public void actionPerformed(ActionEvent e) {
                    System.exit(0);
        	}
	    });
        pane.setOpaque(false);
        
        pane.setBounds(0, 54, 800, 600);
		//pane.setForeground(Color.white);
        pane.setBackground(Color.pink);
        //jPanel2.add(closeButton);
        panel_1.add(closeButton);

        jLayeredPane1.add(jPanel2);
        jLabel1 = new JLabel();
        jPanel1.setLayout(new BorderLayout());
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main.jpg"))); // NOI18N
        jPanel1.add(jLabel1, BorderLayout.CENTER);
        jLayeredPane1.add(jPanel1);
        
        //frame.add(jLayeredPane1, BorderLayout.CENTER);
        frame.getContentPane().add(jLayeredPane1,BorderLayout.CENTER);
        frame.setBounds(200,100,800,657);
		frame.setUndecorated(true);
		frame.addMouseListener(new MouseAdapter() {
			@Override
			public void mousePressed(MouseEvent e) {
				xOld = e.getX();
				yOld = e.getY();
			}
		});
		frame.addMouseMotionListener(new MouseMotionAdapter() {
			@Override
			public void mouseDragged(MouseEvent e) {
				int xOnScreen = e.getXOnScreen();
				int yOnScreen = e.getYOnScreen();
				int xx = xOnScreen - xOld;
				int yy = yOnScreen - yOld;
				frame.setLocation(xx, yy);
			}
		});
    }
    
    public void show(){
    	 frame.setVisible(true);
    }
}
